import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { handoverApi } from "../../services/handoverApi";
import { usersApi } from "../../services/usersApi";
import { useAuthStore } from "../../stores/auth";
import type { AuthUser } from "../../types/auth";
import type { HandoverDocumentLink, OperationalContact, OperationalTask, OrganizationDocument, RoleResponsibility } from "../../types/handover";
import { ErrorBanner, VaultFrame } from "./HandoverFrame";
import { formatDate } from "./handoverFormat";
import { Field } from "./HandoverRoles";
import { useHandoverData } from "./useHandoverData";

const categories = ["Governance", "Finance", "Sporting Operations", "Facilities", "Compliance", "Communications", "Fundraising", "Membership", "Other"];

export default function HandoverRoleDetail() {
	const { roleId = "" } = useParams();
	const navigate = useNavigate();
	const [searchParams] = useSearchParams();
	const isAdmin = useAuthStore((state) => state.currentUser?.role === "Admin");
	const { data, error, loading, reload, setError } = useHandoverData();
	const [documents, setDocuments] = useState<OrganizationDocument[]>([]);
	const [users, setUsers] = useState<AuthUser[]>([]);
	const [responsibility, setResponsibility] = useState<RoleResponsibility | null>(null);
	const [task, setTask] = useState<OperationalTask | null>(null);
	const [contact, setContact] = useState<OperationalContact | null>(null);
	const [showLink, setShowLink] = useState<string | "role" | null>(null);
	const [showHandover, setShowHandover] = useState(searchParams.get("startHandover") === "1");
	useEffect(() => { void handoverApi.getDocuments().then(setDocuments).catch(() => setDocuments([])); if (isAdmin) void usersApi.getUsers().then(setUsers).catch(() => setUsers([])); }, [isAdmin]);
	const role = data?.roles.find((item) => item.id === roleId);
	const roleResponsibilities = useMemo(() => data?.responsibilities.filter((item) => item.operationalRoleId === roleId) ?? [], [data, roleId]);
	const roleTasks = data?.tasks.filter((item) => item.operationalRoleId === roleId) ?? [];
	const roleContacts = data?.contacts.filter((item) => item.operationalRoleId === roleId || roleResponsibilities.some((responsibility) => responsibility.id === item.responsibilityId)) ?? [];
	const roleLinks = data?.documentLinks.filter((item) => item.operationalRoleId === roleId || roleResponsibilities.some((responsibility) => responsibility.id === item.responsibilityId)) ?? [];
	const roleHandovers = data?.handovers.filter((item) => item.operationalRoleId === roleId) ?? [];
	async function act(operation: () => Promise<unknown>) { try { await operation(); await reload(); setError(""); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "The action failed."); } }
	if (loading) return <VaultFrame><p className="text-sm text-slate-500">Loading role…</p></VaultFrame>;
	if (!role) return <VaultFrame><ErrorBanner message={error || "This operational role is unavailable."} /></VaultFrame>;
	return <VaultFrame>
		<div className="surface-card p-5 sm:p-6"><Link to="/handover/roles" className="text-sm font-bold text-yepset-700">← Operational roles</Link><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-3xl font-black">{role.name}</h2>{!role.isActive && <span className="rounded-full bg-slate-200 px-2 py-1 text-xs font-bold">Inactive</span>}</div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{role.description || "No description has been added."}</p></div>{isAdmin && <button className="btn-primary" onClick={() => setShowHandover(true)}>Start handover</button>}</div><dl className="mt-5 grid gap-3 sm:grid-cols-3"><Summary label="Primary owner" value={users.find((user) => user.id === role.primaryOwnerUserId)?.email ?? (role.primaryOwnerUserId ? "Assigned member" : "Unassigned")} /><Summary label="Supporting owners" value={role.supportingOwnerUserIds.length ? `${role.supportingOwnerUserIds.length} assigned` : "None"} /><Summary label="Continuity warnings" value={String(data?.warnings.filter((warning) => warning.entityId === role.id).length ?? 0)} /></dl></div>
		{error && <ErrorBanner message={error} />}

		<Section title="Responsibilities" action={isAdmin ? <button className="btn-secondary" onClick={() => setResponsibility(emptyResponsibility(roleId))}>Add responsibility</button> : undefined}>
			<div className="space-y-3">{roleResponsibilities.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h4 className="font-black">{item.title}</h4>{item.isCritical && <span className="rounded-full bg-red-100 px-2 py-0.5 text-xs font-bold text-red-700">Critical</span>}<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">{item.category}</span></div><p className="mt-1 text-sm text-slate-600">{item.summary}</p><p className="mt-2 text-xs text-slate-500">{item.frequency || "No frequency"}{item.typicalDueDateDescription ? ` · ${item.typicalDueDateDescription}` : ""}</p></div>{isAdmin && <div className="flex gap-2"><button className="text-sm font-bold text-yepset-700" onClick={() => setShowLink(item.id)}>Link document</button><button className="text-sm font-bold text-yepset-700" onClick={() => setResponsibility({ ...item })}>Edit</button></div>}</div><LinkedDocuments links={roleLinks.filter((link) => link.responsibilityId === item.id)} documents={documents} onUnlink={isAdmin ? (id) => act(() => handoverApi.unlinkDocument(id)) : undefined} /></article>)}{roleResponsibilities.length === 0 && <Empty text="No responsibilities have been added to this role." />}</div>
		</Section>

		<Section title="Role documents" action={isAdmin ? <div className="flex gap-2"><Link className="btn-secondary" to={`/handover/documents/new?returnTo=${encodeURIComponent(`/handover/roles/${roleId}`)}`}>Create document</Link><button className="btn-secondary" onClick={() => setShowLink("role")}>Link existing</button></div> : undefined}>
			<LinkedDocuments links={roleLinks.filter((link) => link.operationalRoleId === roleId)} documents={documents} onUnlink={isAdmin ? (id) => act(() => handoverApi.unlinkDocument(id)) : undefined} />
		</Section>

		<Section title="Current and upcoming tasks" action={isAdmin ? <button className="btn-secondary" onClick={() => setTask(emptyTask(roleId))}>Add task</button> : undefined}>
			<div className="divide-y divide-slate-100">{roleTasks.slice(0, 6).map((item) => <div key={item.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-bold">{item.title}</p><p className="text-sm text-slate-500">{item.status.replace(/([A-Z])/g, " $1").trim()} · {formatDate(item.dueAt)}</p></div>{item.status !== "Completed" && <button className="btn-secondary" onClick={() => void act(() => handoverApi.saveTask({ ...item, status: "Completed" }))}>Complete</button>}{isAdmin && <button className="text-sm font-bold text-yepset-700" onClick={() => setTask({ ...item })}>Edit</button>}</div>)}{roleTasks.length === 0 && <Empty text="No operational tasks for this role." />}</div>
		</Section>

		{isAdmin && <Section title="Important contacts" action={<button className="btn-secondary" onClick={() => setContact(emptyContact(roleId))}>Add contact</button>}>
			<div className="grid gap-3 md:grid-cols-2">{roleContacts.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="font-black">{item.name}</p><p className="text-sm text-slate-500">{item.organizationName}</p></div><button className="text-sm font-bold text-yepset-700" onClick={() => setContact({ ...item })}>Edit</button></div><p className="mt-2 text-sm">{item.purpose || "Purpose not recorded"}</p><div className="mt-2 text-xs text-slate-500">{item.email}{item.email && item.phone ? " · " : ""}{item.phone}</div></article>)}{roleContacts.length === 0 && <Empty text="No operational contacts for this role." />}</div>
		</Section>}

		<Section title="Handovers"><div className="space-y-3">{roleHandovers.map((handover) => <Link key={handover.id} to={`/handover/records/${handover.id}`} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><p className="font-bold">{handover.status.replace(/([A-Z])/g, " $1").trim()}</p><p className="text-sm text-slate-500">Started {formatDate(handover.startedAt)} · {handover.items.length} items</p></div><span>›</span></Link>)}{roleHandovers.length === 0 && <Empty text="No formal handovers have been recorded." />}</div></Section>

		{responsibility && <ResponsibilityModal value={responsibility} onClose={() => setResponsibility(null)} onSave={(value) => act(() => handoverApi.saveResponsibility(value)).then(() => setResponsibility(null))} />}
		{task && <TaskModal value={task} users={users} responsibilities={roleResponsibilities} onClose={() => setTask(null)} onSave={(value) => act(() => handoverApi.saveTask(value)).then(() => setTask(null))} />}
		{contact && <ContactModal value={contact} responsibilities={roleResponsibilities} onClose={() => setContact(null)} onSave={(value) => act(() => handoverApi.saveContact(value)).then(() => setContact(null))} />}
		{showLink && <LinkDocumentModal target={showLink} roleId={roleId} documents={documents} returnTo={`/handover/roles/${roleId}`} onClose={() => setShowLink(null)} onSave={(link) => act(() => handoverApi.linkDocument(link)).then(() => setShowLink(null))} />}
		{showHandover && <HandoverModal roleId={roleId} outgoingUserId={searchParams.get("outgoing") || role.primaryOwnerUserId} incomingUserId={searchParams.get("incoming") || null} users={users} onClose={() => setShowHandover(false)} onSave={async (request) => { try { const created = await handoverApi.createHandover(request); navigate(`/handover/records/${created.id}`); } catch (createError) { setError(createError instanceof Error ? createError.message : "Failed to create handover."); } }} />}
	</VaultFrame>;
}

function Section({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="surface-card p-5 sm:p-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-black">{title}</h3>{action}</div>{children}</section>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-1 truncate font-black">{value}</dd></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-500">{text}</p>; }

function LinkedDocuments({ links, documents, onUnlink }: { links: HandoverDocumentLink[]; documents: OrganizationDocument[]; onUnlink?: (id: string) => void }) {
	if (links.length === 0) return <Empty text="No organisation documents are linked here." />;
	return <div className="mt-3 space-y-2">{links.sort((a, b) => a.displayOrder - b.displayOrder).map((link) => { const document = documents.find((item) => item.id === link.organizationDocumentId); return <div key={link.id} className={`flex items-center gap-3 rounded-xl border p-3 ${!document || document.isArchived ? "border-amber-300 bg-amber-50" : "border-blue-100 bg-blue-50/50"}`}><span className="text-blue-700">▤</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{document?.title ?? "Unavailable document"}</p><p className="text-xs text-slate-500">{link.purpose || "No link purpose"}{link.isRequiredForHandover ? " · Required for handover" : ""}{document?.isArchived ? " · Archived" : ""}</p></div>{document && <Link className="text-sm font-bold text-yepset-700" to={`/handover/documents/${document.id}`}>Open</Link>}{onUnlink && <button className="text-sm font-bold text-red-600" onClick={() => onUnlink(link.id)}>Unlink</button>}</div>; })}</div>;
}

function ResponsibilityModal({ value, onClose, onSave }: { value: RoleResponsibility; onClose: () => void; onSave: (value: RoleResponsibility) => Promise<void> }) {
	const [item, setItem] = useState(value); const [saving, setSaving] = useState(false);
	return <Modal title={item.id ? "Edit responsibility" : "Add responsibility"} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); setSaving(true); void onSave(item).finally(() => setSaving(false)); }} className="space-y-4"><Field label="Title"><input required value={item.title} onChange={(event) => setItem({ ...item, title: event.target.value })} /></Field><Field label="Short summary"><textarea rows={3} value={item.summary} onChange={(event) => setItem({ ...item, summary: event.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Category"><select value={item.category} onChange={(event) => setItem({ ...item, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Frequency"><input value={item.frequency} placeholder="Monthly, annual, ongoing…" onChange={(event) => setItem({ ...item, frequency: event.target.value })} /></Field></div><Field label="Typical due date"><input value={item.typicalDueDateDescription} placeholder="e.g. Before 30 June" onChange={(event) => setItem({ ...item, typicalDueDateDescription: event.target.value })} /></Field><div className="flex gap-5"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={item.isCritical} onChange={(event) => setItem({ ...item, isCritical: event.target.checked })} /> Critical</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={item.isActive} onChange={(event) => setItem({ ...item, isActive: event.target.checked })} /> Active</label></div><Actions saving={saving} onClose={onClose} /></form></Modal>;
}

function TaskModal({ value, users, responsibilities, onClose, onSave }: { value: OperationalTask; users: AuthUser[]; responsibilities: RoleResponsibility[]; onClose: () => void; onSave: (value: OperationalTask) => Promise<void> }) {
	const [item, setItem] = useState(value); const [saving, setSaving] = useState(false);
	return <Modal title={item.id ? "Edit operational task" : "Add operational task"} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); setSaving(true); void onSave(item).finally(() => setSaving(false)); }} className="space-y-4"><Field label="Task title"><input required value={item.title} onChange={(event) => setItem({ ...item, title: event.target.value })} /></Field><Field label="Description"><textarea rows={3} value={item.description} onChange={(event) => setItem({ ...item, description: event.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Responsibility"><select value={item.responsibilityId ?? ""} onChange={(event) => setItem({ ...item, responsibilityId: event.target.value || null })}><option value="">Role-level task</option>{responsibilities.map((responsibility) => <option key={responsibility.id} value={responsibility.id}>{responsibility.title}</option>)}</select></Field><Field label="Due date"><input type="datetime-local" value={toLocalInput(item.dueAt)} onChange={(event) => setItem({ ...item, dueAt: event.target.value ? new Date(event.target.value).toISOString() : null })} /></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Status"><select value={item.status} onChange={(event) => setItem({ ...item, status: event.target.value as OperationalTask["status"] })}>{["NotStarted", "InProgress", "Blocked", "Completed", "Cancelled"].map((status) => <option key={status}>{status}</option>)}</select></Field><Field label="Recurrence"><select value={item.recurrence} onChange={(event) => setItem({ ...item, recurrence: event.target.value as OperationalTask["recurrence"] })}>{["None", "Weekly", "Monthly", "Yearly", "CustomInterval"].map((recurrence) => <option key={recurrence}>{recurrence}</option>)}</select></Field></div><fieldset><legend className="text-sm font-bold text-slate-700">Assigned members</legend><div className="mt-2 max-h-36 space-y-2 overflow-y-auto rounded-xl border border-slate-200 p-3">{users.filter((user) => user.isActive).map((user) => <label key={user.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.assignedUserIds.includes(user.id)} onChange={(event) => setItem({ ...item, assignedUserIds: event.target.checked ? [...item.assignedUserIds, user.id] : item.assignedUserIds.filter((id) => id !== user.id) })} />{user.email}</label>)}</div></fieldset><Actions saving={saving} onClose={onClose} /></form></Modal>;
}

function ContactModal({ value, responsibilities, onClose, onSave }: { value: OperationalContact; responsibilities: RoleResponsibility[]; onClose: () => void; onSave: (value: OperationalContact) => Promise<void> }) {
	const [item, setItem] = useState(value); const [saving, setSaving] = useState(false);
	return <Modal title={item.id ? "Edit operational contact" : "Add operational contact"} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); setSaving(true); void onSave(item).finally(() => setSaving(false)); }} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Name"><input required value={item.name} onChange={(event) => setItem({ ...item, name: event.target.value })} /></Field><Field label="Organisation"><input value={item.organizationName} onChange={(event) => setItem({ ...item, organizationName: event.target.value })} /></Field></div><Field label="Purpose"><input value={item.purpose} onChange={(event) => setItem({ ...item, purpose: event.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Email"><input type="email" value={item.email} onChange={(event) => setItem({ ...item, email: event.target.value })} /></Field><Field label="Phone"><input value={item.phone} onChange={(event) => setItem({ ...item, phone: event.target.value })} /></Field></div><Field label="Responsibility"><select value={item.responsibilityId ?? ""} onChange={(event) => setItem({ ...item, responsibilityId: event.target.value || null })}><option value="">Role-level contact</option>{responsibilities.map((responsibility) => <option key={responsibility.id} value={responsibility.id}>{responsibility.title}</option>)}</select></Field><Field label="Notes"><textarea rows={3} value={item.notes} onChange={(event) => setItem({ ...item, notes: event.target.value })} /></Field><p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Only record information necessary for legitimate organisation operations. Contacts are not visible to Players.</p><Actions saving={saving} onClose={onClose} /></form></Modal>;
}

function LinkDocumentModal({ target, roleId, documents, returnTo, onClose, onSave }: { target: string; roleId: string; documents: OrganizationDocument[]; returnTo: string; onClose: () => void; onSave: (link: HandoverDocumentLink) => Promise<void> }) {
	const [documentId, setDocumentId] = useState(""); const [purpose, setPurpose] = useState(""); const [required, setRequired] = useState(false); const [saving, setSaving] = useState(false);
	return <Modal title="Link organisation document" onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); setSaving(true); void onSave({ id: "", operationalRoleId: target === "role" ? roleId : null, responsibilityId: target === "role" ? null : target, organizationDocumentId: documentId, purpose, isRequiredForHandover: required, displayOrder: 0 }).finally(() => setSaving(false)); }} className="space-y-4"><Field label="Existing document"><select required value={documentId} onChange={(event) => setDocumentId(event.target.value)}><option value="">Select a document</option>{documents.filter((document) => !document.isArchived).map((document) => <option key={document.id} value={document.id}>{document.title}</option>)}</select></Field><Field label="Why this document is relevant"><input value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder="e.g. Monthly submission process" /></Field><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={required} onChange={(event) => setRequired(event.target.checked)} /> Required in formal handovers</label><Link className="block rounded-xl border border-dashed border-blue-300 bg-blue-50 p-3 text-center text-sm font-bold text-blue-800" to={`/handover/documents/new?returnTo=${encodeURIComponent(returnTo)}`}>Create a new organisation document</Link><Actions saving={saving} onClose={onClose} /></form></Modal>;
}

function HandoverModal({ roleId, outgoingUserId, incomingUserId, users, onClose, onSave }: { roleId: string; outgoingUserId: string | null; incomingUserId: string | null; users: AuthUser[]; onClose: () => void; onSave: (request: { operationalRoleId: string; outgoingUserId: string | null; incomingUserId: string | null; dueAt: string | null; notes: string; accessTransfers: string[]; additionalItems: string[] }) => Promise<void> }) {
	const [outgoing, setOutgoing] = useState(outgoingUserId ?? ""); const [incoming, setIncoming] = useState(incomingUserId ?? ""); const [dueAt, setDueAt] = useState(""); const [notes, setNotes] = useState(""); const [accessTransfers, setAccessTransfers] = useState(""); const [additionalItems, setAdditionalItems] = useState(""); const [saving, setSaving] = useState(false);
	return <Modal title="Start formal handover" onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); setSaving(true); void onSave({ operationalRoleId: roleId, outgoingUserId: outgoing || null, incomingUserId: incoming || null, dueAt: dueAt ? new Date(dueAt).toISOString() : null, notes, accessTransfers: accessTransfers.split("\n").map((item) => item.trim()).filter(Boolean), additionalItems: additionalItems.split("\n").map((item) => item.trim()).filter(Boolean) }).finally(() => setSaving(false)); }} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Outgoing owner"><select value={outgoing} onChange={(event) => setOutgoing(event.target.value)}><option value="">Not known</option>{users.map((user) => <option key={user.id} value={user.id}>{user.email}</option>)}</select></Field><Field label="Incoming owner"><select value={incoming} onChange={(event) => setIncoming(event.target.value)}><option value="">Not known</option>{users.map((user) => <option key={user.id} value={user.id}>{user.email}</option>)}</select></Field></div><Field label="Due date"><input type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></Field><Field label="Notes"><textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></Field><Field label="Access transfers (one per line)"><textarea rows={4} value={accessTransfers} onChange={(event) => setAccessTransfers(event.target.value)} placeholder="Club bank account administrator\nLeague portal account owner" /></Field><Field label="Additional checklist items (one per line)"><textarea rows={3} value={additionalItems} onChange={(event) => setAdditionalItems(event.target.value)} placeholder="Introduce incoming owner to league secretary" /></Field><p className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-800">Never include passwords, recovery codes, API keys, MFA secrets or other credentials. Describe the account and transfer action only.</p><Actions saving={saving} onClose={onClose} label="Start handover" /></form></Modal>;
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3"><div className="mx-auto my-6 w-full max-w-2xl rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-start justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onClose}>✕</button></div>{children}</div></div>; }
function Actions({ saving, onClose, label = "Save" }: { saving: boolean; onClose: () => void; label?: string }) { return <div className="flex justify-end gap-2 border-t pt-4"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={saving}>{saving ? "Saving…" : label}</button></div>; }
function emptyResponsibility(roleId: string): RoleResponsibility { return { id: "", operationalRoleId: roleId, title: "", summary: "", category: "Other", frequency: "", typicalDueDateDescription: "", isCritical: false, isActive: true }; }
function emptyTask(roleId: string): OperationalTask { return { id: "", operationalRoleId: roleId, responsibilityId: null, title: "", description: "", dueAt: null, assignedUserIds: [], status: "NotStarted", completedAt: null, completedByUserId: null, completionNotes: "", recurrence: "None", recurrenceInterval: 1, customIntervalDays: null, nextOccurrenceAt: null }; }
function emptyContact(roleId: string): OperationalContact { return { id: "", operationalRoleId: roleId, responsibilityId: null, name: "", organizationName: "", purpose: "", email: "", phone: "", notes: "", isActive: true }; }
function toLocalInput(value: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
